import {Dimensions, StyleSheet} from 'react-native'

import {globalContext} from '../../../DependencyInjection/AppContext'

const commonTheme = globalContext.theme.value
//TODO: стилизовать под один стандарт и отпочковываться от нее
export const BottomStyles = StyleSheet.create({
    container: {
        width: '100%',
        position: 'absolute',
        height: commonTheme.bottomArea.height,
        bottom: 0,
        backgroundColor: commonTheme.navigation.navigationColor,
        alignSelf: 'center',
        alignItems: 'center',
        alignContent: 'center',
        flexDirection: 'row',
        flex: 1,
    },
    containerSpaceBetween: {
        justifyContent: 'space-between',
    },
    containerCenter: {
        justifyContent: 'center',
    },
    activeButton: {
        bottom: 0,
        padding: 18,
        elevation: 4,
        borderRadius: 8,
        marginLeft: 15,
        marginRight: 15,
        backgroundColor: commonTheme.buttons.background('valid'),
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'center',
        width: 350,   
    },
    cancelButton: {
        bottom: 0,
        padding: 18,
        elevation: 4,
        borderRadius: 8,
        marginLeft: 15,
        marginRight: 15,
        backgroundColor: commonTheme.colors.darkBackground,
        borderColor: commonTheme.colors.main,
        borderWidth: 2,
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'center',
        width: 350, 
    },
    secondaryButton: {
        bottom: 0,
        padding: 18,
        elevation: 4,
        borderRadius: 8,
        marginLeft: 15,
        marginRight: 15,
        backgroundColor: commonTheme.colors.darkBackground,
        borderColor: commonTheme.colors.accent,
        borderWidth: 2,
        justifyContent: 'center',
        alignItems: 'center',
        width: 350, 
    },
    secondaryButtonForCancelPayment: {
        bottom: 0,
        padding: 18,
        // elevation: 4,
        borderRadius: 8,
        marginLeft: 15,
        marginRight: 15,
        backgroundColor: 'transparent',
        borderColor: commonTheme.colors.accent,
        borderWidth: 2,
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'center',
        width: 350, 
    },
    secondaryButtonForCancelPurchase: {
        bottom: 0,
        padding: 18,
        elevation: 4,
        borderRadius: 8,
        marginLeft: 15,
        marginRight: 15,
        backgroundColor: commonTheme.colors.backgroundColor,
        borderColor: commonTheme.colors.accent,
        borderWidth: 2,
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'center',
        width: 350, 
    },
    disabledButton: {
        bottom: 0,
        padding: 18,
        elevation: 4,
        borderRadius: 8,
        marginLeft: 15,
        marginRight: 15,
        backgroundColor: commonTheme.colors.backgroundColor,
        borderColor: commonTheme.colors.backgroundColor,
        borderWidth: 2,
        justifyContent: 'center',
        alignItems: 'center',
        alignSelf: 'center',
        width: 350, 
        shadowColor: 'transparent',
    },
    textStyle: {
        fontFamily: 'Montserrat-Bold',
        fontSize: 24,
        color: commonTheme.colors.backgroundColor,
        fontWeight: '600',
    },
    disabledTextStyle: {
        fontFamily: 'Montserrat-Bold',
        fontSize: 24,
        color: commonTheme.colors.darkBackground,
        fontWeight: '600',
    },
    textStyleCancel: {
        fontFamily: 'Montserrat-Bold',
        fontSize: 24,
        color: commonTheme.colors.main,
        fontWeight: '600',
    },
    textStyleSecondary: {
        fontFamily: 'Montserrat-Bold',
        fontSize: 24,
        color: commonTheme.colors.accent,
        fontWeight: '600',
    },
})